### ISSUE TITLE
at Board.moveCandy()

### ISSUE THREAD

**Issue by ynuquang** [ynuquang/OOP-CandyCrush#8]
> CLICKED AT 4 3
> CLICKED AT 3 3
> 1 3 1 3 3 
> 3 5 1 3 4 
> 4 1 2 1 4 
> 2 5 5 5 3 
> 1 1 2 1 3 
> 
> CHECKING GRID:
> 1 1 1 1 2 
> 1 1 1 1 1 
> 1 1 1 1 1 
> 1 1 2 3 1 
> 1 2 1 1 1 
> 
> 
> 1 1 1 1 1 
> 1 1 2 2 1 
> 1 1 1 1 2 
> 1 1 1 1 1 
> 1 1 1 1 2 
> 
> /***************************/
> 1 3 1 3 3 
> 3 5 1 3 4 
> 4 1 2 1 4 
> 2 **5 5 5** 3 
> 1 1 2 1 3 
> 
> Combo formed?: 3
> Swap javafx.animation.ParallelTransition@1bc57673
> SWAP: Coordinate [4 3] <-> Coordinate [3 3]
> Crush javafx.animation.ParallelTransition@c4eeac1
> _1 **3 1 3** 3 
> 3 **5 1 3** 4 
> 4 **1 2 1** 4 
> 2 **0 0 0** 3 
> 1 1 2 1 3_ 
> **moveCandy**
> _0 0 0 0 0 
> 3 3 1 3 4 
> 4 5 1 3 4 
> 2 1 2 1 3 
> 1 1 2 1 3_ 

Isn't is supposed to be
_**1** 0 0 0 **3** 
3 3 1 3 4 
4 5 1 3 4 
2 1 2 1 3 
1 1 2 1 3_ 
after moveCandy ?

**Comment by phuongduyphan** [comment]
Stupid 0-base !
